### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by gollariel** [Chocorean/authmod#14]
After installing latest version v2.5, I can execute register multiple times, but I can not login... (strategy file).
Also, file config/authmod_players.csv was filled after first register and it not empty

**Comment by Chocorean** [comment]
Thank you, I’ll be fixing this in the afternoon
My apologies

**Comment by Mcdostone** [comment]
I think I fixed this issue with the commit https://github.com/Chocorean/authmod/commit/0d9f478de229c5d48614be5bc62805ff8b9bb752

**Comment by gollariel** [comment]
Sorry, I was trying version 2.5 with mysql, and it also do not works:

```
Query - conn:18(M)  - "INSERT INTO players(email, password, uuid, username) VALUES(?,?)"
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getSqlException(ExceptionMapper.java:211) ~[ExceptionMapper.class:?]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.setParameter(MariaDbPreparedStatementClient.java:438) ~[MariaDbPreparedStatementClient.class:?]
	at org.mariadb.jdbc.BasePrepareStatement.setNull(BasePrepareStatement.java:569) ~[BasePrepareStatement.class:?]
	at org.mariadb.jdbc.BasePrepareStatement.setString(BasePrepareStatement.java:1375) ~[BasePrepareStatement.class:?]
	at io.chocorean.authmod.authentication.db.PlayersDAO.create(PlayersDAO.java:25) ~[PlayersDAO.class:?]
	at io.chocorean.authmod.authentication.datasource.DatabaseSourceStrategy.add(DatabaseSourceStrategy.java:48) [DatabaseSourceStrategy.class:?]
	at io.chocorean.authmod.authentication.AuthModule.register(AuthModule.java:57) [AuthModule.class:?]
	at io.chocorean.authmod.command.RegisterCommand.func_184881_a(RegisterCommand.java:66) [RegisterCommand.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:83) [CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[21:45:58] [Server thread/ERROR] [FML]: Something when wrong. Please contact the admins.
```
on register command

**Comment by Mcdostone** [comment]
I'm on it !

**Comment by turret001** [comment]
I'm still having this issue. any updates on the fix? thanks!

**Comment by Mcdostone** [comment]
We don't have release the new version yet, be patient ;)

**Comment by Mcdostone** [comment]
[2.6](https://github.com/Chocorean/authmod/releases/tag/2.6) is available
